### ISSUE TITLE
[Rubocop Formatter] rubocop command finished with exit(7)

### ISSUE THREAD

**Issue by J-ad** [fnando/sublime-rubocop-formatter#2]
Hi, I was using this package for a couple of months then it suddenly stopped formatting files exiting with error: 
`[Rubocop Formatter] rubocop command finished with exit(7)`

Whole trace from Sublime Text 3 console:
```
[Rubocop Formatter] input file is /Users/****.rb
[Rubocop Formatter] current scope: source.ruby comment.line.number-sign.ruby punctuation.definition.comment.ruby 
[Rubocop Formatter] using root dir as /Users/***
[Rubocop Formatter] using command ['rubocop', '--auto-correct-all', '/Users/***.rb']
[Rubocop Formatter] rubocop command finished with exit(7)
```

If I run `rubocop -a` in terminal it works fine.
I'm using SublimeLinter with rubocop and it highlights errors correctly. 

I'm using rubocop 1.0 in my project

Any ideas on how to debug this issue?

**Comment by fnando** [comment]
The lowercase `-a` is not the same as `--auto-correct-all`, which is shorten as `-A`. Can you try that and see if you get any output on the terminal?

I'm going to improve the plugin to save a log file with errors, so it's easier to understand why it's failing.

**Comment by fnando** [comment]
Please upgrade the plugin to the latest version and enable debugging mode. The plugin now logs the command output, so it's easier to know what's up.

**Comment by J-ad** [comment]
Hi, managed to solve this issue so I'll post the solution: 
it turns out that I had some issues with my environment, `gem list` returned some previously deleted rubocop versions, and probably that caused the formatter to fail. I basically had to reinstall rvm and ruby and delete all contents of .rvm folder.

Plugin works perfectly now, thanks!
